"""initial commit

Revision ID: 7392b74f0b27
Revises: 
Create Date: 2021-09-29 17:51:21.787357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7392b74f0b27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('amount', sa.String(length=16), nullable=True),
    sa.Column('amount_one', sa.String(length=16), nullable=True),
    sa.Column('amount_two', sa.String(length=16), nullable=True),
    sa.Column('amount_three', sa.String(length=16), nullable=True),
    sa.Column('amount_four', sa.String(length=16), nullable=True),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset')
    # ### end Alembic commands ###
